<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ID_repviol',
'Etat',
'R_nomcomplet',
'R_adresse',
'R_tel',
'R_nationalite',
'R_age',
'R_NivScolaire',
'R_ActivitePro',
'R_antesced',
'R_junck' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ID_repviol' => array( 'import_field' ),
'Etat' => array( 'import_field1' ),
'R_nomcomplet' => array( 'import_field2' ),
'R_adresse' => array( 'import_field3' ),
'R_tel' => array( 'import_field4' ),
'R_nationalite' => array( 'import_field5' ),
'R_age' => array( 'import_field6' ),
'R_NivScolaire' => array( 'import_field7' ),
'R_ActivitePro' => array( 'import_field8' ),
'R_antesced' => array( 'import_field9' ),
'R_junck' => array( 'import_field10' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ) ),
'cellMaps' => array(  ) ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'ID_repviol',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Etat',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'R_nomcomplet',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'R_adresse',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'R_tel',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'R_nationalite',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'R_age',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'R_NivScolaire',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'R_ActivitePro',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'R_antesced',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'R_junck',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>