<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'num_dossier',
'nom_assist',
'SourceInfo',
'Date_ecoute',
'vcin',
'victime',
'coupable',
'rel_coup_victime',
'date_viol',
'viol_eco',
'viol_corp',
'viol_sexuel',
'viol_psych',
'viol_juris',
'conseq_corp',
'consequ_psych',
'conseq_enf',
'demand_vict',
'svce_prop',
'ms3cellenffem',
'ms3oblpaye',
'ms3obstacles',
'sachcellenffem',
'sachcopyrap',
'rapporoui',
'encscepublic',
'encscpuboui',
'n3cellenffem',
'n3pression',
'n3docs',
'tribcellenffem',
'tribpression',
'tribobligpaye',
'remarques',
'conseq_ecosocial' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'num_dossier' => array( 'import_field' ),
'nom_assist' => array( 'import_field1' ),
'SourceInfo' => array( 'import_field2' ),
'Date_ecoute' => array( 'import_field3' ),
'vcin' => array( 'import_field4' ),
'victime' => array( 'import_field5' ),
'coupable' => array( 'import_field6' ),
'rel_coup_victime' => array( 'import_field7' ),
'date_viol' => array( 'import_field8' ),
'viol_eco' => array( 'import_field9' ),
'viol_corp' => array( 'import_field10' ),
'viol_sexuel' => array( 'import_field11' ),
'viol_psych' => array( 'import_field12' ),
'viol_juris' => array( 'import_field13' ),
'conseq_corp' => array( 'import_field16' ),
'consequ_psych' => array( 'import_field17' ),
'conseq_enf' => array( 'import_field20' ),
'demand_vict' => array( 'import_field21' ),
'svce_prop' => array( 'import_field22' ),
'ms3cellenffem' => array( 'import_field23' ),
'ms3oblpaye' => array( 'import_field24' ),
'ms3obstacles' => array( 'import_field25' ),
'sachcellenffem' => array( 'import_field26' ),
'sachcopyrap' => array( 'import_field27' ),
'rapporoui' => array( 'import_field28' ),
'encscepublic' => array( 'import_field29' ),
'encscpuboui' => array( 'import_field30' ),
'n3cellenffem' => array( 'import_field31' ),
'n3pression' => array( 'import_field32' ),
'n3docs' => array( 'import_field33' ),
'tribcellenffem' => array( 'import_field34' ),
'tribpression' => array( 'import_field35' ),
'tribobligpaye' => array( 'import_field36' ),
'remarques' => array( 'import_field37' ),
'conseq_ecosocial' => array( 'import_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field16',
'import_field17',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field14' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field14' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field16',
'import_field17',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field16',
'import_field17',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'num_dossier',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'nom_assist',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'SourceInfo',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Date_ecoute',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'vcin',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'victime',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'coupable',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'rel_coup_victime',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'date_viol',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'viol_eco',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'viol_corp',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'viol_sexuel',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'viol_psych',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'viol_juris',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'conseq_corp',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'consequ_psych',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'conseq_enf',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'demand_vict',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'svce_prop',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'ms3cellenffem',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'ms3oblpaye',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'ms3obstacles',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'sachcellenffem',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'sachcopyrap',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'rapporoui',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'encscepublic',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'encscpuboui',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'n3cellenffem',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'n3pression',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'n3docs',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'tribcellenffem',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'tribpression',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'tribobligpaye',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'remarques',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'conseq_ecosocial',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>