<?php
			$optionsArray = array( 'totals' => array( 'num_dossier' => array( 'totalsType' => '' ),
'nom_assist' => array( 'totalsType' => '' ),
'SourceInfo' => array( 'totalsType' => '' ),
'Date_ecoute' => array( 'totalsType' => '' ),
'vcin' => array( 'totalsType' => '' ),
'victime' => array( 'totalsType' => '' ),
'coupable' => array( 'totalsType' => '' ),
'rel_coup_victime' => array( 'totalsType' => '' ),
'date_viol' => array( 'totalsType' => '' ),
'viol_eco' => array( 'totalsType' => '' ),
'viol_corp' => array( 'totalsType' => '' ),
'viol_sexuel' => array( 'totalsType' => '' ),
'viol_psych' => array( 'totalsType' => '' ),
'viol_juris' => array( 'totalsType' => '' ),
'conseq_corp' => array( 'totalsType' => '' ),
'consequ_psych' => array( 'totalsType' => '' ),
'conseq_ecosocial' => array( 'totalsType' => '' ),
'conseq_enf' => array( 'totalsType' => '' ),
'demand_vict' => array( 'totalsType' => '' ),
'svce_prop' => array( 'totalsType' => '' ),
'ms3cellenffem' => array( 'totalsType' => '' ),
'ms3oblpaye' => array( 'totalsType' => '' ),
'ms3obstacles' => array( 'totalsType' => '' ),
'sachcellenffem' => array( 'totalsType' => '' ),
'sachcopyrap' => array( 'totalsType' => '' ),
'rapporoui' => array( 'totalsType' => '' ),
'encscepublic' => array( 'totalsType' => '' ),
'encscpuboui' => array( 'totalsType' => '' ),
'n3cellenffem' => array( 'totalsType' => '' ),
'n3pression' => array( 'totalsType' => '' ),
'n3docs' => array( 'totalsType' => '' ),
'tribcellenffem' => array( 'totalsType' => '' ),
'tribpression' => array( 'totalsType' => '' ),
'tribobligpaye' => array( 'totalsType' => '' ),
'remarques' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'num_dossier',
'nom_assist',
'SourceInfo',
'Date_ecoute',
'vcin',
'victime',
'coupable',
'rel_coup_victime',
'date_viol',
'viol_eco',
'viol_corp',
'viol_sexuel',
'viol_psych',
'viol_juris',
'conseq_corp',
'consequ_psych',
'conseq_enf',
'demand_vict',
'svce_prop',
'ms3cellenffem',
'ms3oblpaye',
'ms3obstacles',
'sachcellenffem',
'sachcopyrap',
'rapporoui',
'encscepublic',
'encscpuboui',
'n3cellenffem',
'n3pression',
'n3docs',
'tribcellenffem',
'tribpression',
'tribobligpaye',
'remarques',
'conseq_ecosocial' ),
'exportFields' => array( 'num_dossier',
'nom_assist',
'SourceInfo',
'Date_ecoute',
'vcin',
'victime',
'coupable',
'rel_coup_victime',
'date_viol',
'viol_eco',
'viol_corp',
'viol_sexuel',
'viol_psych',
'viol_juris',
'conseq_corp',
'consequ_psych',
'conseq_enf',
'demand_vict',
'svce_prop',
'ms3cellenffem',
'ms3oblpaye',
'ms3obstacles',
'sachcellenffem',
'sachcopyrap',
'rapporoui',
'encscepublic',
'encscpuboui',
'n3cellenffem',
'n3pression',
'n3docs',
'tribcellenffem',
'tribpression',
'tribobligpaye',
'remarques',
'conseq_ecosocial' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'num_dossier' => array( 'export_field' ),
'nom_assist' => array( 'export_field1' ),
'SourceInfo' => array( 'export_field2' ),
'Date_ecoute' => array( 'export_field3' ),
'vcin' => array( 'export_field4' ),
'victime' => array( 'export_field5' ),
'coupable' => array( 'export_field6' ),
'rel_coup_victime' => array( 'export_field7' ),
'date_viol' => array( 'export_field8' ),
'viol_eco' => array( 'export_field9' ),
'viol_corp' => array( 'export_field10' ),
'viol_sexuel' => array( 'export_field11' ),
'viol_psych' => array( 'export_field12' ),
'viol_juris' => array( 'export_field13' ),
'conseq_corp' => array( 'export_field16' ),
'consequ_psych' => array( 'export_field17' ),
'conseq_enf' => array( 'export_field20' ),
'demand_vict' => array( 'export_field21' ),
'svce_prop' => array( 'export_field22' ),
'ms3cellenffem' => array( 'export_field23' ),
'ms3oblpaye' => array( 'export_field24' ),
'ms3obstacles' => array( 'export_field25' ),
'sachcellenffem' => array( 'export_field26' ),
'sachcopyrap' => array( 'export_field27' ),
'rapporoui' => array( 'export_field28' ),
'encscepublic' => array( 'export_field29' ),
'encscpuboui' => array( 'export_field30' ),
'n3cellenffem' => array( 'export_field31' ),
'n3pression' => array( 'export_field32' ),
'n3docs' => array( 'export_field33' ),
'tribcellenffem' => array( 'export_field34' ),
'tribpression' => array( 'export_field35' ),
'tribobligpaye' => array( 'export_field36' ),
'remarques' => array( 'export_field37' ),
'conseq_ecosocial' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field16',
'export_field17',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field16',
'export_field17',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field16',
'export_field17',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'num_dossier',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'nom_assist',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'SourceInfo',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Date_ecoute',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'vcin',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'victime',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'coupable',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'rel_coup_victime',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'date_viol',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'viol_eco',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'viol_corp',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'viol_sexuel',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'viol_psych',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'viol_juris',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'conseq_corp',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'consequ_psych',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'conseq_enf',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'demand_vict',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'svce_prop',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'ms3cellenffem',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'ms3oblpaye',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'ms3obstacles',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'sachcellenffem',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'sachcopyrap',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'rapporoui',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'encscepublic',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'encscpuboui',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'n3cellenffem',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'n3pression',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'n3docs',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'tribcellenffem',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'tribpression',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'tribobligpaye',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'remarques',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'conseq_ecosocial',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>