<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'nom_assist',
'SourceInfo',
'Date_ecoute',
'vcin',
'victime',
'coupable',
'rel_coup_victime',
'date_viol',
'viol_eco',
'viol_corp',
'viol_sexuel',
'viol_psych',
'viol_juris',
'conseq_corp',
'consequ_psych',
'conseq_enf',
'ms3cellenffem',
'ms3oblpaye',
'ms3obstacles',
'sachcellenffem',
'sachcopyrap',
'rapporoui',
'encscepublic',
'encscpuboui',
'n3cellenffem',
'n3pression',
'n3docs',
'tribcellenffem',
'tribpression',
'remarques',
'conseq_ecosocial' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'nom_assist' => array( 'integrated_edit_field' ),
'SourceInfo' => array( 'integrated_edit_field1' ),
'Date_ecoute' => array( 'integrated_edit_field2' ),
'vcin' => array( 'integrated_edit_field3' ),
'victime' => array( 'integrated_edit_field4' ),
'coupable' => array( 'integrated_edit_field5' ),
'rel_coup_victime' => array( 'integrated_edit_field6' ),
'date_viol' => array( 'integrated_edit_field7' ),
'viol_eco' => array( 'integrated_edit_field8' ),
'viol_corp' => array( 'integrated_edit_field9' ),
'viol_sexuel' => array( 'integrated_edit_field10' ),
'viol_psych' => array( 'integrated_edit_field11' ),
'viol_juris' => array( 'integrated_edit_field12' ),
'conseq_corp' => array( 'integrated_edit_field15' ),
'consequ_psych' => array( 'integrated_edit_field16' ),
'conseq_enf' => array( 'integrated_edit_field19' ),
'ms3cellenffem' => array( 'integrated_edit_field22' ),
'ms3oblpaye' => array( 'integrated_edit_field23' ),
'ms3obstacles' => array( 'integrated_edit_field24' ),
'sachcellenffem' => array( 'integrated_edit_field25' ),
'sachcopyrap' => array( 'integrated_edit_field26' ),
'rapporoui' => array( 'integrated_edit_field27' ),
'encscepublic' => array( 'integrated_edit_field28' ),
'encscpuboui' => array( 'integrated_edit_field29' ),
'n3cellenffem' => array( 'integrated_edit_field30' ),
'n3pression' => array( 'integrated_edit_field31' ),
'n3docs' => array( 'integrated_edit_field32' ),
'tribcellenffem' => array( 'integrated_edit_field33' ),
'tribpression' => array( 'integrated_edit_field34' ),
'remarques' => array( 'integrated_edit_field36' ),
'conseq_ecosocial' => array( 'integrated_edit_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'section',
'section1',
'section2',
'section3',
'integrated_edit_field36' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field7',
'integrated_edit_field6',
'integrated_edit_field5',
'integrated_edit_field4',
'integrated_edit_field3',
'integrated_edit_field2',
'integrated_edit_field1' ),
'section1' => array( 'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field9',
'integrated_edit_field8',
'integrated_edit_field12' ),
'section2' => array( 'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field13',
'integrated_edit_field16' ),
'section3' => array( 'section4',
'section5',
'section6',
'section7',
'section8' ),
'section4' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28' ),
'section6' => array( 'integrated_edit_field22' ),
'section7' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'section5' => array( 'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31' ),
'section8' => array( 'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'section' => 'grid',
'section1' => 'grid',
'section2' => 'grid',
'section3' => 'grid',
'integrated_edit_field36' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field11' => 'section1',
'integrated_edit_field10' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field15' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field16' => 'section2',
'section4' => 'section3',
'section5' => 'section3',
'section6' => 'section3',
'section7' => 'section3',
'section8' => 'section3',
'integrated_edit_field26' => 'section4',
'integrated_edit_field27' => 'section4',
'integrated_edit_field28' => 'section4',
'integrated_edit_field22' => 'section6',
'integrated_edit_field23' => 'section7',
'integrated_edit_field24' => 'section7',
'integrated_edit_field25' => 'section7',
'integrated_edit_field29' => 'section5',
'integrated_edit_field30' => 'section5',
'integrated_edit_field31' => 'section5',
'integrated_edit_field32' => 'section8',
'integrated_edit_field33' => 'section8',
'integrated_edit_field34' => 'section8' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'section4' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section5' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section6' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section7' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'section8' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field26' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field27' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field28' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field22' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field23' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field24' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section7',
'cellId' => 'c1' ),
'integrated_edit_field29' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field30' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field32' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field33' => array( 'location' => 'section8',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section8',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field19',
'integrated_edit_field22',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34',
'integrated_edit_field36',
'integrated_edit_field13' ),
'section' => array( 'section',
'section1',
'section2',
'section3',
'section4',
'section5',
'section6',
'section7',
'section8' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'section1',
'section2',
'section3',
'integrated_edit_field36' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 8 ),
'section1' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 5 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 4 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section4',
'section5',
'section6',
'section7',
'section8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section6' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section7' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section8' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section',
'section1',
'section2',
'section3',
'integrated_edit_field36' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'section4',
'section5',
'section6',
'section7',
'section8' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26',
'integrated_edit_field27',
'integrated_edit_field28' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section7' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field31' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section8' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32',
'integrated_edit_field33',
'integrated_edit_field34' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 't_dossier',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field' => array( 'field' => 'nom_assist',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'nom_assist',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'SourceInfo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'SourceInfo',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'Date_ecoute',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Date_ecoute',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'vcin',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'vcin',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'victime',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'coupable',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'coupable',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'rel_coup_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rel_coup_victime',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'date_viol',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'date_viol',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'viol_eco',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'viol_eco',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'viol_corp',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'viol_corp',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'viol_sexuel',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'viol_sexuel',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'viol_psych',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'viol_psych',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'viol_juris',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'viol_juris',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'conseq_corp',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'conseq_corp',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'consequ_psych',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'consequ_psych',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field19' => array( 'field' => 'conseq_enf',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'conseq_enf',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field22' => array( 'field' => 'ms3cellenffem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ms3cellenffem',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field23' => array( 'field' => 'ms3oblpaye',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ms3oblpaye',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field24' => array( 'field' => 'ms3obstacles',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ms3obstacles',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field25' => array( 'field' => 'sachcellenffem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sachcellenffem',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field26' => array( 'field' => 'sachcopyrap',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'sachcopyrap',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field27' => array( 'field' => 'rapporoui',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'rapporoui',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field28' => array( 'field' => 'encscepublic',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'encscepublic',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field29' => array( 'field' => 'encscpuboui',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'encscpuboui',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field30' => array( 'field' => 'n3cellenffem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'n3cellenffem',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field31' => array( 'field' => 'n3pression',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'n3pression',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field32' => array( 'field' => 'n3docs',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'n3docs',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field33' => array( 'field' => 'tribcellenffem',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tribcellenffem',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field34' => array( 'field' => 'tribpression',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'tribpression',
'table' => 't_dossier',
'type' => 3 ) ),
'integrated_edit_field36' => array( 'field' => 'remarques',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'conseq_ecosocial',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'conseq_ecosocial',
'table' => 't_dossier',
'type' => 3 ) ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => ' المعلومات الخاصة  بالملف ',
'type' => 0 ),
'location' => 'section',
'mobileDisplay' => '',
'padding' => array( 'left' => '33px' ) ),
'section1' => array( 'type' => 'section',
'title' => array( 'text' => 'تصنيف العنف',
'type' => 0 ),
'location' => 'section1' ),
'section2' => array( 'type' => 'section',
'title' => array( 'text' => 'الآثار المترتبة عن العنف',
'type' => 0 ),
'location' => 'section2' ),
'section3' => array( 'type' => 'section',
'title' => array( 'text' => 'الممارسات الفضلى للفاعلين العموميين المسجلة من طرف الضحية:',
'type' => 0 ),
'location' => 'section3' ),
'section4' => array( 'type' => 'section',
'title' => array( 'text' => 'هل بلغت أو لجأت للسلطات',
'type' => 0 ),
'location' => 'section6' ),
'section5' => array( 'type' => 'section',
'title' => array( 'text' => 'في حالة الضابطة القضائية الشرطة أو الدرك الملكي',
'type' => 0 ),
'location' => 'section7' ),
'section6' => array( 'type' => 'section',
'title' => array( 'text' => 'في حالة النيابة العامة ',
'type' => 0 ),
'location' => 'section4' ),
'section7' => array( 'type' => 'section',
'title' => array( 'text' => 'في حالة المحكمة ',
'type' => 0 ),
'location' => 'section5' ),
'section8' => array( 'type' => 'section',
'title' => array( 'text' => 'في حالة مصالح الصحة العمومية ',
'type' => 0 ),
'location' => 'section8' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>