<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'Enfants' => array( 'preview' => true ) ),
'totals' => array( 'victime_CIN' => array( 'totalsType' => '' ),
'Nom_victime' => array( 'totalsType' => '' ),
'Adresse_victime' => array( 'totalsType' => '' ),
'Tel_victime' => array( 'totalsType' => '' ),
'Age_victime' => array( 'totalsType' => '' ),
'Region_victime' => array( 'totalsType' => '' ),
'TypeHabitation_victime' => array( 'totalsType' => '' ),
'NivScolaire_victime' => array( 'totalsType' => '' ),
'ActivitePro_victime' => array( 'totalsType' => '' ),
'EtatCivil_victime' => array( 'totalsType' => '' ),
'VictDate_marriage' => array( 'totalsType' => '' ),
'Periode_marriage' => array( 'totalsType' => '' ),
'Date_divorce' => array( 'totalsType' => '' ),
'Type_divorce' => array( 'totalsType' => '' ),
'Nbr_enfants' => array( 'totalsType' => '' ),
'NbrEnfant_Gracon' => array( 'totalsType' => '' ),
'NbrEnfant_Fille' => array( 'totalsType' => '' ),
'Victime_ENceinte' => array( 'totalsType' => '' ),
'Enfant_list' => array( 'totalsType' => '' ),
'CouvSocial_victime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'victime_CIN',
'Nom_victime',
'Adresse_victime',
'Tel_victime',
'Age_victime',
'Region_victime',
'TypeHabitation_victime',
'NivScolaire_victime',
'ActivitePro_victime',
'EtatCivil_victime',
'VictDate_marriage',
'Periode_marriage',
'Date_divorce',
'Type_divorce',
'Nbr_enfants',
'NbrEnfant_Gracon',
'NbrEnfant_Fille',
'Victime_ENceinte',
'Enfant_list',
'CouvSocial_victime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'victime_CIN' => array( 'simple_grid_field',
'simple_grid_field20' ),
'Nom_victime' => array( 'simple_grid_field1',
'simple_grid_field21' ),
'Adresse_victime' => array( 'simple_grid_field2',
'simple_grid_field22' ),
'Tel_victime' => array( 'simple_grid_field3',
'simple_grid_field23' ),
'Age_victime' => array( 'simple_grid_field4',
'simple_grid_field24' ),
'Region_victime' => array( 'simple_grid_field5',
'simple_grid_field25' ),
'TypeHabitation_victime' => array( 'simple_grid_field6',
'simple_grid_field26' ),
'NivScolaire_victime' => array( 'simple_grid_field7',
'simple_grid_field27' ),
'ActivitePro_victime' => array( 'simple_grid_field8',
'simple_grid_field28' ),
'EtatCivil_victime' => array( 'simple_grid_field9',
'simple_grid_field29' ),
'VictDate_marriage' => array( 'simple_grid_field10',
'simple_grid_field30' ),
'Periode_marriage' => array( 'simple_grid_field11',
'simple_grid_field31' ),
'Date_divorce' => array( 'simple_grid_field12',
'simple_grid_field32' ),
'Type_divorce' => array( 'simple_grid_field13',
'simple_grid_field33' ),
'Nbr_enfants' => array( 'simple_grid_field14',
'simple_grid_field34' ),
'NbrEnfant_Gracon' => array( 'simple_grid_field15',
'simple_grid_field35' ),
'NbrEnfant_Fille' => array( 'simple_grid_field16',
'simple_grid_field36' ),
'Victime_ENceinte' => array( 'simple_grid_field17',
'simple_grid_field37' ),
'Enfant_list' => array( 'simple_grid_field18',
'simple_grid_field38' ),
'CouvSocial_victime' => array( 'simple_grid_field19',
'simple_grid_field39' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info' ),
'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field20',
'simple_grid_field',
'simple_grid_field21',
'simple_grid_field1',
'simple_grid_field22',
'simple_grid_field2',
'simple_grid_field23',
'simple_grid_field3',
'simple_grid_field24',
'simple_grid_field4',
'simple_grid_field25',
'simple_grid_field5',
'simple_grid_field26',
'simple_grid_field6',
'simple_grid_field27',
'simple_grid_field7',
'simple_grid_field28',
'simple_grid_field8',
'simple_grid_field29',
'simple_grid_field9',
'simple_grid_field30',
'simple_grid_field10',
'simple_grid_field31',
'simple_grid_field11',
'simple_grid_field32',
'simple_grid_field12',
'simple_grid_field33',
'simple_grid_field13',
'simple_grid_field34',
'simple_grid_field14',
'simple_grid_field35',
'simple_grid_field15',
'simple_grid_field36',
'simple_grid_field16',
'simple_grid_field37',
'simple_grid_field17',
'simple_grid_field38',
'simple_grid_field18',
'simple_grid_field39',
'simple_grid_field19' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'simple_grid_field20' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field19' => 'grid' ),
'itemLocations' => array( 'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'master_info' => array( 'master_info' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19' ),
'grid_field_label' => array( 'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'victime_CIN_fieldheadercolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'Nom_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Adresse_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'Tel_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'Age_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'Region_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'TypeHabitation_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'NivScolaire_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'ActivitePro_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'EtatCivil_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'VictDate_marriage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'Periode_marriage_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'Date_divorce_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'Type_divorce_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'Nbr_enfants_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'NbrEnfant_Gracon_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'NbrEnfant_Fille_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'Victime_ENceinte_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'Enfant_list_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'CouvSocial_victime_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'victime_CIN_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Nom_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Adresse_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Tel_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Age_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Region_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'TypeHabitation_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'NivScolaire_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'ActivitePro_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'EtatCivil_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'VictDate_marriage_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'Periode_marriage_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'Date_divorce_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'Type_divorce_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'Nbr_enfants_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'NbrEnfant_Gracon_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'NbrEnfant_Fille_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'Victime_ENceinte_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'Enfant_list_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'CouvSocial_victime_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 20,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'victime_CIN',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'victime_CIN',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'Nom_victime',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'Nom_victime',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'Adresse_victime',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Adresse_victime',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'Tel_victime',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Tel_victime',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'Age_victime',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Age_victime',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'Region_victime',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Region_victime',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'TypeHabitation_victime',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'TypeHabitation_victime',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'NivScolaire_victime',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'NivScolaire_victime',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'ActivitePro_victime',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'ActivitePro_victime',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'EtatCivil_victime',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'EtatCivil_victime',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'VictDate_marriage',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'VictDate_marriage',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'Periode_marriage',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'Periode_marriage',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'Date_divorce',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Date_divorce',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'Type_divorce',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'Type_divorce',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'Nbr_enfants',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'Nbr_enfants',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'NbrEnfant_Gracon',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'NbrEnfant_Gracon',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'NbrEnfant_Fille',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'NbrEnfant_Fille',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'Victime_ENceinte',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'Victime_ENceinte',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'Enfant_list',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'Enfant_list',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'CouvSocial_victime',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'CouvSocial_victime',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'Enfants' => 'true' ) ),
'simple_grid_field' => array( 'field' => 'victime_CIN',
'type' => 'grid_field' ),
'simple_grid_field20' => array( 'type' => 'grid_field_label',
'field' => 'victime_CIN' ),
'simple_grid_field1' => array( 'field' => 'Nom_victime',
'type' => 'grid_field' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'Nom_victime' ),
'simple_grid_field2' => array( 'field' => 'Adresse_victime',
'type' => 'grid_field' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'Adresse_victime' ),
'simple_grid_field3' => array( 'field' => 'Tel_victime',
'type' => 'grid_field' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'Tel_victime' ),
'simple_grid_field4' => array( 'field' => 'Age_victime',
'type' => 'grid_field' ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'Age_victime' ),
'simple_grid_field5' => array( 'field' => 'Region_victime',
'type' => 'grid_field' ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'Region_victime' ),
'simple_grid_field6' => array( 'field' => 'TypeHabitation_victime',
'type' => 'grid_field' ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'TypeHabitation_victime' ),
'simple_grid_field7' => array( 'field' => 'NivScolaire_victime',
'type' => 'grid_field' ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'NivScolaire_victime' ),
'simple_grid_field8' => array( 'field' => 'ActivitePro_victime',
'type' => 'grid_field' ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'ActivitePro_victime' ),
'simple_grid_field9' => array( 'field' => 'EtatCivil_victime',
'type' => 'grid_field' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'EtatCivil_victime' ),
'simple_grid_field10' => array( 'field' => 'VictDate_marriage',
'type' => 'grid_field' ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'VictDate_marriage' ),
'simple_grid_field11' => array( 'field' => 'Periode_marriage',
'type' => 'grid_field' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'Periode_marriage' ),
'simple_grid_field12' => array( 'field' => 'Date_divorce',
'type' => 'grid_field' ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'Date_divorce' ),
'simple_grid_field13' => array( 'field' => 'Type_divorce',
'type' => 'grid_field' ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'Type_divorce' ),
'simple_grid_field14' => array( 'field' => 'Nbr_enfants',
'type' => 'grid_field' ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'Nbr_enfants' ),
'simple_grid_field15' => array( 'field' => 'NbrEnfant_Gracon',
'type' => 'grid_field' ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'NbrEnfant_Gracon' ),
'simple_grid_field16' => array( 'field' => 'NbrEnfant_Fille',
'type' => 'grid_field' ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'NbrEnfant_Fille' ),
'simple_grid_field17' => array( 'field' => 'Victime_ENceinte',
'type' => 'grid_field' ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'Victime_ENceinte' ),
'simple_grid_field18' => array( 'field' => 'Enfant_list',
'type' => 'grid_field' ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'Enfant_list' ),
'simple_grid_field19' => array( 'field' => 'CouvSocial_victime',
'type' => 'grid_field' ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'CouvSocial_victime' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>