<?php
			$optionsArray = array( 'totals' => array( 'victime_CIN' => array( 'totalsType' => '' ),
'Nom_victime' => array( 'totalsType' => '' ),
'Adresse_victime' => array( 'totalsType' => '' ),
'Tel_victime' => array( 'totalsType' => '' ),
'Age_victime' => array( 'totalsType' => '' ),
'Region_victime' => array( 'totalsType' => '' ),
'TypeHabitation_victime' => array( 'totalsType' => '' ),
'NivScolaire_victime' => array( 'totalsType' => '' ),
'ActivitePro_victime' => array( 'totalsType' => '' ),
'EtatCivil_victime' => array( 'totalsType' => '' ),
'VictDate_marriage' => array( 'totalsType' => '' ),
'Periode_marriage' => array( 'totalsType' => '' ),
'Date_divorce' => array( 'totalsType' => '' ),
'Type_divorce' => array( 'totalsType' => '' ),
'Nbr_enfants' => array( 'totalsType' => '' ),
'NbrEnfant_Gracon' => array( 'totalsType' => '' ),
'NbrEnfant_Fille' => array( 'totalsType' => '' ),
'Victime_ENceinte' => array( 'totalsType' => '' ),
'Enfant_list' => array( 'totalsType' => '' ),
'CouvSocial_victime' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'victime_CIN',
'Nom_victime',
'Adresse_victime',
'Tel_victime',
'Age_victime',
'Region_victime',
'TypeHabitation_victime',
'NivScolaire_victime',
'ActivitePro_victime',
'EtatCivil_victime',
'VictDate_marriage',
'Periode_marriage',
'Date_divorce',
'Type_divorce',
'Nbr_enfants',
'NbrEnfant_Gracon',
'NbrEnfant_Fille',
'Victime_ENceinte',
'Enfant_list',
'CouvSocial_victime' ),
'exportFields' => array( 'victime_CIN',
'Nom_victime',
'Adresse_victime',
'Tel_victime',
'Age_victime',
'Region_victime',
'TypeHabitation_victime',
'NivScolaire_victime',
'ActivitePro_victime',
'EtatCivil_victime',
'VictDate_marriage',
'Periode_marriage',
'Date_divorce',
'Type_divorce',
'Nbr_enfants',
'NbrEnfant_Gracon',
'NbrEnfant_Fille',
'Victime_ENceinte',
'Enfant_list',
'CouvSocial_victime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'victime_CIN' => array( 'export_field' ),
'Nom_victime' => array( 'export_field1' ),
'Adresse_victime' => array( 'export_field2' ),
'Tel_victime' => array( 'export_field3' ),
'Age_victime' => array( 'export_field4' ),
'Region_victime' => array( 'export_field5' ),
'TypeHabitation_victime' => array( 'export_field6' ),
'NivScolaire_victime' => array( 'export_field7' ),
'ActivitePro_victime' => array( 'export_field8' ),
'EtatCivil_victime' => array( 'export_field9' ),
'VictDate_marriage' => array( 'export_field10' ),
'Periode_marriage' => array( 'export_field11' ),
'Date_divorce' => array( 'export_field12' ),
'Type_divorce' => array( 'export_field13' ),
'Nbr_enfants' => array( 'export_field14' ),
'NbrEnfant_Gracon' => array( 'export_field15' ),
'NbrEnfant_Fille' => array( 'export_field16' ),
'Victime_ENceinte' => array( 'export_field17' ),
'Enfant_list' => array( 'export_field18' ),
'CouvSocial_victime' => array( 'export_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'victime_CIN',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'Nom_victime',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Adresse_victime',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Tel_victime',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Age_victime',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Region_victime',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'TypeHabitation_victime',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'NivScolaire_victime',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'ActivitePro_victime',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'EtatCivil_victime',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'VictDate_marriage',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'Periode_marriage',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Date_divorce',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Type_divorce',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Nbr_enfants',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'NbrEnfant_Gracon',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'NbrEnfant_Fille',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Victime_ENceinte',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Enfant_list',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'CouvSocial_victime',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>