<?php
			$optionsArray = array( 'master' => array( 'Enfants' => array( 'preview' => true ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'victime_CIN',
'Nom_victime',
'Adresse_victime',
'Tel_victime',
'Age_victime',
'Region_victime',
'TypeHabitation_victime',
'NivScolaire_victime',
'ActivitePro_victime',
'EtatCivil_victime',
'VictDate_marriage',
'Periode_marriage',
'Date_divorce',
'Type_divorce',
'Nbr_enfants',
'NbrEnfant_Gracon',
'NbrEnfant_Fille',
'Victime_ENceinte',
'Enfant_list',
'CouvSocial_victime' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'victime_CIN' => array( 'integrated_edit_field' ),
'Nom_victime' => array( 'integrated_edit_field1' ),
'Adresse_victime' => array( 'integrated_edit_field2' ),
'Tel_victime' => array( 'integrated_edit_field3' ),
'Age_victime' => array( 'integrated_edit_field4' ),
'Region_victime' => array( 'integrated_edit_field5' ),
'TypeHabitation_victime' => array( 'integrated_edit_field6' ),
'NivScolaire_victime' => array( 'integrated_edit_field7' ),
'ActivitePro_victime' => array( 'integrated_edit_field8' ),
'EtatCivil_victime' => array( 'integrated_edit_field9' ),
'VictDate_marriage' => array( 'integrated_edit_field10' ),
'Periode_marriage' => array( 'integrated_edit_field11' ),
'Date_divorce' => array( 'integrated_edit_field12' ),
'Type_divorce' => array( 'integrated_edit_field13' ),
'Nbr_enfants' => array( 'integrated_edit_field14' ),
'NbrEnfant_Gracon' => array( 'integrated_edit_field15' ),
'NbrEnfant_Fille' => array( 'integrated_edit_field16' ),
'Victime_ENceinte' => array( 'integrated_edit_field17' ),
'Enfant_list' => array( 'integrated_edit_field18' ),
'CouvSocial_victime' => array( 'integrated_edit_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'section',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19' ),
'section' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'master_info' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field1' => 'grid',
'integrated_edit_field2' => 'grid',
'integrated_edit_field3' => 'grid',
'integrated_edit_field4' => 'grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field9' => 'grid',
'section' => 'grid',
'integrated_edit_field14' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field16' => 'grid',
'integrated_edit_field17' => 'grid',
'integrated_edit_field18' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field10' => 'section',
'integrated_edit_field11' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field13' => 'section' ),
'itemLocations' => array( 'master_info' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19' ),
'section' => array( 'section' ),
'master_info' => array( 'master_info' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'section',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'master_info',
'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'section',
'integrated_edit_field14',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18',
'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'Victime',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field' => array( 'field' => 'victime_CIN',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'victime_CIN',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field1' => array( 'field' => 'Nom_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Nom_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'Adresse_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Adresse_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'Tel_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Tel_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field4' => array( 'field' => 'Age_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Age_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field5' => array( 'field' => 'Region_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Region_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field6' => array( 'field' => 'TypeHabitation_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'TypeHabitation_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field7' => array( 'field' => 'NivScolaire_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'NivScolaire_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field8' => array( 'field' => 'ActivitePro_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'ActivitePro_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field9' => array( 'field' => 'EtatCivil_victime',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'EtatCivil_victime',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field10' => array( 'field' => 'VictDate_marriage',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'VictDate_marriage',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'Periode_marriage',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Periode_marriage',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field12' => array( 'field' => 'Date_divorce',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Date_divorce',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field13' => array( 'field' => 'Type_divorce',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Type_divorce',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field14' => array( 'field' => 'Nbr_enfants',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Nbr_enfants',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'NbrEnfant_Gracon',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'NbrEnfant_Gracon',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field16' => array( 'field' => 'NbrEnfant_Fille',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'NbrEnfant_Fille',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field17' => array( 'field' => 'Victime_ENceinte',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'Victime_ENceinte',
'table' => 'Victime',
'type' => 3 ) ),
'integrated_edit_field18' => array( 'field' => 'Enfant_list',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'CouvSocial_victime',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'section' => array( 'type' => 'section',
'title' => array( 'text' => 'زواج أو طلاق الناجية من العنف:',
'type' => 0 ),
'location' => 'section' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'Enfants' => 'true' ) ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>