on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: regatec.azurecr.io
        username: ${{ secrets.acr_regatec_username }}
        password: ${{ secrets.acr_regatec_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t regatec.azurecr.io/admcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push regatec.azurecr.io/admcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_admcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep admclusteraf34 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace admclusteraf34`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: admclusteraf34
        container-registry-url: regatec.azurecr.io
        container-registry-username: ${{ secrets.acr_regatec_username }}
        container-registry-password: ${{ secrets.acr_regatec_password }}
        secret-name: admclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: admclusteraf34
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          regatec.azurecr.io/admcluster:${{ github.sha }}
        imagepullsecrets: |
          admclusterdockerauth
